### ISSUE TITLE
Use TemplateSelector for matching machine templates

### ISSUE THREAD

**Issue by bsctl** [clastix/cluster-api-kamaji-proxmox#3]
In `ProxmoxMachineTemplate`, use `TemplateSelector` for matching the machine template:

```yaml
spec:
  template:
    spec:
      numCores: 2
      numSockets: 2
      pool: sample-capi-pool
      sourceNode: labs
      storage: local
      # templateID: 109
     templateSelector:
        matchTags:
          - "ubuntu-nobe-kube-1.31.4"
...
```

Passed tags must be an exact 1:1 match with the tags on the template you want to use. If multiple VM templates with the same set of tags are found, provisioning will fail.
