### ISSUE TITLE
Improve User Provisioning

### ISSUE THREAD

**Issue by bsctl** [clastix/cluster-api-kamaji-proxmox#6]
Only user name and key are passed to the `_kubeadm-config-template.tpl`

```yaml
users:
{{- range .nodePool.users }}
- name: {{ .name | quote }}
  sshAuthorizedKeys:
  {{- range .sshAuthorizedKeys }}
  - {{ . | quote }}
  {{- end }}
  sudo: {{ .sudo | quote }}
```

Need to pass all the expected parameters for a better user management

```yaml
{{- if .nodePool.users }}
users:
{{- range .nodePool.users }}
  - {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
```
